name: Dev Landing

on:
  push:
    branches: [ "dev-landing" ]

  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy to S3 bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          bucket_name=`aws ssm get-parameter --name "/autosql/dev/frontend/landing" | jq ".Parameter.Value" | tr -d '"'`
          echo $bucket_name
          aws s3 cp landing/ s3://$bucket_name \
              --recursive \
              --region ap-northeast-2 \
              
