name: Dev Landing

on:
  push:
    branches: [ "dev-landing" ]

  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Copy to S3 bucket
        run: |
          bucket_name=`aws ssm get-parameter --name "/autosql/dev/frontend/landing" | jq ".Parameter.Value" | tr -d '"'`
          echo $bucket_name
          aws s3 cp landing/ s3://$bucket_name \
              --recursive \
              --region ap-northeast-2 \
              
